### PR TITLE
Feat page index adjustment

### PR DESCRIPTION
**Pull request by mukrop**
Proposition of textual changes on the title page: Lead paragraph and feature list.

* The general idea stands on the messaging we created for the ICCC marketing materials.
* The wording in the individual feature sections is heavily based on the original wording.
* The collapsibles in the feature blocks were dropped as multiple people found it counter-intuitive that the opened text would contain important links.
* It's not ideal, but I believe an improvement over the current state.

Unfortunately, I don't have currently set up the local development environment, so cannot guarantee it will compile flawlessly (apologies!).

### CODE REVIEW

**Comment by J08nY** [comment]
Looks good, though the texts for the vulnerability and notifications features are quite a bit longer than the other ones, giving it an unbalanced look. I will shorten them (the notifications mainly) and add appropriate small buttons for the vuln one to go to CVE/CPE search.

image

**Comment by mukrop** [comment]
You're right, thanks. Adjust as you see fit.

**Comment by J08nY** [comment]
Made it nicer.

image

**Comment by J08nY** [comment]
Huh, this somehow broke the logo display at the index page.
Not sure what happened but will fix it.

image

**Comment by J08nY** [comment]
Ok fixed.

**Pull request merged**
