### PR TITLE
Docs

### LINKED ISSUE #195: Docs
The goal is to prepare documentation of the stable parts. Some thoughts:

- Use sphinx
- `index.rst`, the rest with markdown
- CI to build docs, some secret to authenticate to some endpoint at seccerts.org, the builded artifacts will be deployed to seccerts.org/docs
- Action to build and push docs on each push to main or just on release?

### PR DESCRIPTION
**Pull request by adamjanovsky**
Closes #195 

## Stuff to sort out

- [x] Release GitHub action should change version numbers in some files here and there (e.g., `docs/conf.py`).
- [x] We should pull CONTRIBUTING.md, README.md, License etc. into docs somehow to avoid duplication
- [x] Prepare docs structure
- [x] ~~Add automatic parsing of module docstrings~~
- [x] automatically create Binder links for notebooks (possibly use [deepnote](deepnote.com)?)
- [x] Write docstrings for `DependencyFinder` and `VulnerabilityDependencyFinder` @GeorgeFI 
- [x] Write docstrings for `dataset` package members
- [x] Write docstrings fro `sample` package members
- [x] Write down tutorial
- [x] Switch `binder` branch to `main` in `conf.py`
- [x] Automatically process `settings.yaml` into `./configuration.md` page 
- [x] Add link to docs on PyPi (`release.yml`) & link to PyPi from `index.md`

## Stuff to do after merging to main

- [ ] See if notebooks work
- [ ] See if all pipelines are ok
- [ ] Release

### CODE REVIEW

**Comment by adamjanovsky** [comment]
@J08nY the minimal sphinx build is running and CI action that builds the docs (and does nothing with them) runs as well.

**Comment by J08nY** [comment]
> * [ ]  Release GitHub action should change version numbers in some files here and there (e.g., `docs/conf.py`).

I do think this is something the maintainer should do, in a single commit across the board and that commit should then become the release commit. Tagged and signed ideally.


> * [ ] We should pull CONTRIBUTING.md, README.md, License etc. into docs somehow to avoid duplication

Symlinks should work.

**Comment by adamjanovsky** [comment]
> > * [ ]   Release GitHub action should change version numbers in some files here and there (e.g., `docs/conf.py`).
> 
> I do think this is something the maintainer should do, in a single commit across the board and that commit should then become the release commit. Tagged and signed ideally.
> 
> > * [ ]  We should pull CONTRIBUTING.md, README.md, License etc. into docs somehow to avoid duplication
> 
> Symlinks should work.

Ad symlinks: ok.
Ad version numbers: Yes, but I want to automate it. Now, I release with https://github.com/crocs-muni/sec-certs/releases/new which creates single, tagged and signed, commit. As a part of that commit, I want GitHub Actions to run some sort of script that would modify the version strings all over the repository with `${{ github.event.release.tag_name }}` content

**Comment by J08nY** [comment]
I don't really see a reason to have that, the page itself can be self-documenting. I think we just need docs for the tool.

**Comment by adamjanovsky** [comment]
> I don't really see a reason to have that, the page itself can be self-documenting. I think we just need docs for the tool.

Ok, 

Btw, I think that the docs layout is finalized. The GitHub action produces the `_build` folder, so you can try to upload its contents somewhere onto web. In the meantime, I'll be populating the docs during long evenings :).

**Comment by adamjanovsky** [comment]
@GeorgeFI Do you think you could squeeze 30 minutes of work into writing down documentation for your two classes `DependencyFinder` and `DependencyVulnerabilityFinder` in `model` package? Here are some requirements:

- Only public method should be documented (`fit`, `transform`, maybe some more that you expose)
- Class should have brief description as well
- The docsting style should be `sphinx-oneline`
- For example, see `SARTransformer` class.

**Pull request merged**
