### PR TITLE
Feat/pymupdf experiment

### LINKED ISSUE #364: Evaluate possible switch from pdftotext to PyMuPDF
We should evaluate whether it's worth switching from `pdftotext` to [PyMuPDF](https://pymupdf.readthedocs.io/en/latest/) for data extraction. We should:

1. @dmacko232 provide code that substitutes [pdftotext conversion](https://github.com/crocs-muni/sec-certs/blob/f59e517490112c8baeb56c81a5869774ad1b821b/src/sec_certs/utils/pdf.py#L73) with an identical functionality achieved using PyMuPDF
2. @adamjanovsky run the new pipeline on full dataset and provide results to @J08nY 
3. @J08nY compare the outputs on both datasets, decide if we should switch

Note: @adamjanovsky will handle the second step instead of originally advertised @GeorgeFI

### PR DESCRIPTION
**Pull request by adamjanovsky**
This closes #364

### CODE REVIEW

**Comment by adamjanovsky** [comment]
@J08nY The datasets computed with `pdftotext` and `pymupdf` are available at Aura, sitting at `/var/tmp/xjanovsk/certs/sec-certs/dataset/toy_dataset_100_certs`; you should have read access there. 

Performance wise, the processing speed seems similar.

**Comment by adamjanovsky** [comment]
@dmacko232 Do we know what are the internal dependencies of `pymupdf` package? Could we drop dependency on `poppler` if we make a switch? 

Also, we're scanning some tables in FIPS documents with some java tool. Could we get rid of the java dependency as well?

**Comment by dmacko232** [comment]
@adamjanovsky Poppler is not dependency. The java thing should not be dependency either I guess in case of pymupdf.

**Comment by adamjanovsky** [comment]
Closing this. The details of what would it take to get pymupdf surpass pdftotext in terms of output quality are described in #364

**Pull request closed without merging**
